# Chapter_01
| DATA STRUCTURE	    |   Dimention      | SPREADSHEET ANALOG     |
|-----------------------|------------------|--------------------------
|       Series          |     1D           |       Column           |
|       DataFrame       |     2D           |       Single Sheet     |
|       Panel           |     3D           |       Multiple Sheets  |

# DataFrame Basics

Note - Very good videos of codebasics for anything in python
https://www.youtube.com/playlist?list=PLeo1K3hjS3uuASpe-1LjfG5f14Bnozjwy


DataQuest Tutorial on Data Analysis:

https://www.dataquest.io/blog/pandas-tutorial-python-2/

Chris Albon notes on Groups: https://chrisalbon.com/python/pandas_apply_operations_to_groups.html

Greg Reda Pandas Tutorial: http://www.gregreda.com/2013/10/26/working-with-pandas-dataframes/

In [61]:
import requests
from ipywidgets import Image

Image(value=requests.get('https://github.com/amitsuneja/PandasForDataAnalystNotes/blob/master/Chapter_01_1st.png?raw=true').content,width=500,height=500)

Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xcd\x00\x00\x03\x1a\x08\x02\x00\x00\x003\xef35\x…

In [62]:
Image(value=requests.get('https://github.com/amitsuneja/PandasForDataAnalystNotes/blob/master/Chapter_01_Panda_axis_diagram.jpg?raw=true').content,width=500,height=500)

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x03\x02\x0…

In [63]:
# https://www.shanelynn.ie/summarising-aggregation-and-grouping-data-in-python-pandas/

# phone_bill.csv is phone records of 5 months

# importing numpy and  pandas library
import pandas as pd
import numpy as np
import dateutil as dtutil
import random
import os

In [64]:
# Reading the CSV file to dataframe
my_phone_data_table = pd.read_csv("D:\\myPythonProjects\\PandaSummarisingAggregatingGrouping\\phone_bill.csv", index_col=0)

In [65]:
my_phone_data_table.head()

                 DATE duration  ITEM    month   network network_type
index
0      15/10/14 06:58   34.429  data  2014-11      data         data
1      15/10/14 06:58       13  call  2014-11  Vodafone       mobile
2      15/10/14 14:46       23  call  2014-11    Meteor       mobile
3      15/10/14 14:48        4  call  2014-11     Tesco       mobile
4      15/10/14 17:27        4  call  2014-11     Tesco       mobile

In [66]:
my_phone_data_table.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 830 entries, 0 to 829
Data columns (total 6 columns):
DATE            830 non-null object
duration        830 non-null object
ITEM            827 non-null object
month           830 non-null object
network         830 non-null object
network_type    827 non-null object
dtypes: object(6)
memory usage: 45.4+ KB

In [67]:
"""
For numeric columns, describe() returns basic statistics: 
the value count, mean, standard deviation, minimum, maximum, and 25th, 50th, and 75th quantiles for the data in a column.

For string columns, describe() returns the value count, the number of unique entries, the most frequently occurring 
value (‘top’), and the number of times the top value occurs (‘freq’)"
"""

my_phone_data_table.describe()

                  DATE duration  ITEM    month network network_type
count              830      830   827      830     830          827
unique             747      222     3        5      10            6
top     16/01/15 18:07        1  call  2014-11   Three       mobile
freq                 6      293   386      230     215          600

In [68]:
"""
Without knowing much about my data let me try to describe the above data once , All knowledge i have that this is some 
Mobile Bill data .

1. my data have 6 Columns.

2. 830 records/rows , But few values are blank ( Remember Blank will not show in clount But NaN will be calculated , 
   SO if any Column have 830 records , it does not mean it has no bad data. Bad Data is blank and NaN both.
   
3. 293 calls are made from this phone are very small calls of 1 sec( I am not sure its seconds or minute) . 

4. Mostly calls were made to vodafone netork.

5. 16/01/15 18:07 is date when phone was used 6 times.

6. This phone was mostly used for calling purpose. 386 calls.
"""
#
print(" ")

In [69]:
"""
Note that strings are loaded as ‘object’ datatypes, because technically, the DataFrame holds a pointer to the string 
data elsewhere in memory. This behaviour is expected, and can be ignored.

To change the datatype of a specific column, use the .astype() function. 
For example, to see the ‘Item Code’ column as a string, use:
data['Item Code'].astype(str)

"""

my_phone_data_table.dtypes

DATE            object
duration        object
ITEM            object
month           object
network         object
network_type    object
dtype: object

In [70]:
# Fetching all the columns Names using df.columns and converting to list to calculate lenght of list. It return a Series
my_phone_data_table.columns

Index(['DATE', 'duration', 'ITEM', 'month', 'network', 'network_type'], dtype='object')

In [71]:
# Converting Series into List and Calculating Lenght
number_of_col_in_phone_data_table = len(list(my_phone_data_table.columns))
print("number of columns in data frame = {}".format(number_of_col_in_phone_data_table))

number of columns in data frame = 6

In [72]:
# Setting the display.max_columns to ensure that it display all columns data
pd.set_option('display.max_columns', number_of_col_in_phone_data_table)

In [73]:
my_phone_data_table.head()

                 DATE duration  ITEM    month   network network_type
index
0      15/10/14 06:58   34.429  data  2014-11      data         data
1      15/10/14 06:58       13  call  2014-11  Vodafone       mobile
2      15/10/14 14:46       23  call  2014-11    Meteor       mobile
3      15/10/14 14:48        4  call  2014-11     Tesco       mobile
4      15/10/14 17:27        4  call  2014-11     Tesco       mobile

In [74]:
# checking number of records in dataframe['column_Name'].count()
number_of_records_in_phone_data_table = my_phone_data_table.index
number_of_records_in_phone_data_table = len(number_of_records_in_phone_data_table)
print("total number of records in table are = {}".format(number_of_records_in_phone_data_table))

total number of records in table are = 830

In [75]:
# setting display.max_rows to ensure that it display records
pd.set_option('display.max_rows', int(number_of_records_in_phone_data_table))

In [76]:
my_phone_data_table

                 DATE duration  ITEM    month    network network_type
index
0      15/10/14 06:58   34.429  data  2014-11       data         data
1      15/10/14 06:58       13  call  2014-11   Vodafone       mobile
2      15/10/14 14:46       23  call  2014-11     Meteor       mobile
3      15/10/14 14:48        4  call  2014-11      Tesco       mobile
4      15/10/14 17:27        4  call  2014-11      Tesco       mobile
5      15/10/14 18:55        4  call  2014-11      Tesco       mobile
6      16/10/14 06:58   34.429  data  2014-11       data         data
7      16/10/14 15:01      602  call  2014-11      Three       mobile
8      16/10/14 15:12     1050  call  2014-11      Three       mobile
9      16/10/14 15:30       19  call  2014-11  voicemail    voicemail
10     16/10/14 16:21     1183  call  2014-11      Three       mobile
11     16/10/14 22:18        1   sms  2014-11     Meteor       mobile
12     16/10/14 22:21        1   sms  2014-11     Meteor       mobile
13     17/10/14 06:58   34.429  data  2014-11                     NaN
14     17/10/14 10:53        1   sms  2014-11      Tesco       mobile
15     17/10/14 11:19        1   sms  2014-11      Tesco       mobile
16     17/10/14 11:20        1   sms  2014-11     Meteor       mobile
17     17/10/14 17:22        1   sms  2014-11   Vodafone       mobile
18     17/10/14 17:23        1   sms  2014-11   Vodafone       mobile
19     17/10/14 17:26       92  call  2014-11      Three       mobile
20     17/10/14 17:29        4  call  2014-11   Vodafone       mobile
21     17/10/14 17:30      375  call  2014-11      Tesco       mobile
22     17/10/14 17:42        1   sms  2014-11   Vodafone       mobile
23     17/10/14 17:44        1   sms  2014-11   Vodafone       mobile
24     17/10/14 17:44        1   sms  2014-11   Vodafone       mobile
25     17/10/14 17:44        1   sms  2014-11   Vodafone       mobile
26     18/10/14 06:58   34.429  data  2014-11       data         data
27     18/10/14 11:51      783  call  2014-11      Tesco       mobile
28     18/10/14 12:06        4  call  2014-11   Vodafone       mobile
29     18/10/14 12:06        3  call  2014-11   Vodafone       mobile
30     18/10/14 13:08      101  call  2014-11   Vodafone       mobile
31     18/10/14 13:10     1714  call  2014-11      Three       mobile
32     18/10/14 14:01       96  call  2014-11  voicemail    voicemail
33     18/10/14 18:52        1   sms  2014-11   Vodafone       mobile
34     18/10/14 20:44      384  call  2014-11      Three       mobile
35     18/10/14 21:04        4  call  2014-11      Three       mobile
36     18/10/14 21:06        1   sms  2014-11      Three       mobile
37     18/10/14 21:23        1   sms  2014-11   Vodafone       mobile
38     18/10/14 22:37        1   sms  2014-11      Three       mobile
39     19/10/14 06:58   34.429  data  2014-11       data         data
40     19/10/14 14:47       53  call  2014-11      Three       mobile
41     19/10/14 15:46       86  call  2014-11      Tesco       mobile
42     19/10/14 16:21       23  call  2014-11      Three       mobile
43     19/10/14 16:30       38  call  2014-11      Three       mobile
44     19/10/14 20:25      428  call  2014-11      Three       mobile
45     20/10/14 06:58   34.429  data  2014-11       data         data
46     20/10/14 09:43       69  call  2014-11  voicemail    voicemail
47     20/10/14 09:43       18  call  2014-11  voicemail    voicemail
48     20/10/14 13:55        3  call  2014-11   Vodafone       mobile
49     20/10/14 13:56        6  call  2014-11   landline     landline
50     20/10/14 18:14        5  call  2014-11      Tesco       mobile
51     20/10/14 18:24      131  call  2014-11   Vodafone       mobile
52     20/10/14 19:59        1   sms  2014-11   Vodafone       mobile
53     20/10/14 20:16        1   sms  2014-11   Vodafone       mobile
54     21/10/14 06:58   34.429  data  2014-11       data         data
55     21/10/14 16:17      550  call  2014-11      Three       mobile
56     22/10/14 06:58   34.429  data  2014-11       data         data
57     22/10/14 12:04        7  call  2014-11      Three       mobile
58     23/10/14 06:58   34.429  data  2014-11       data         data
59     23/10/14 08:34     1940  call  2014-11   landline     landline
60     23/10/14 09:45      281  call  2014-11     Meteor       mobile
61     23/10/14 10:46        1   sms  2014-11      Tesco       mobile
62     23/10/14 10:54        1   sms  2014-11   Vodafone       mobile
63     23/10/14 11:17        1   sms  2014-11   Vodafone       mobile
64     23/10/14 11:25       24  call  2014-11   Vodafone       mobile
65     23/10/14 17:48      263  call  2014-11     Meteor       mobile
66     24/10/14 06:58   34.429  data  2014-11       data         data
67     24/10/14 13:35        1   sms  2014-11   Vodafone       mobile
68     24/10/14 13:39        1   sms  2014-11   Vodafone       mobile
69     24/10/14 13:39        1   sms  2014-11   Vodafone       mobile
70     24/10/14 13:47        1   sms  2014-11   Vodafone       mobile
71     24/10/14 13:48        1   sms  2014-11   Vodafone       mobile
72     24/10/14 13:50        1   sms  2014-11   Vodafone       mobile
73     24/10/14 13:57        1   sms  2014-11   Vodafone       mobile
74     24/10/14 13:57        1   sms  2014-11   Vodafone       mobile
75     24/10/14 14:20        1   sms  2014-11      Three       mobile
76     24/10/14 14:27        1   sms  2014-11   Vodafone       mobile
77     24/10/14 18:29        1   sms  2014-11   Vodafone       mobile
78     24/10/14 18:33      387  call  2014-11      Tesco       mobile
79     24/10/14 18:40        1   sms  2014-11   Vodafone       mobile
80     25/10/14 06:58   34.429  data  2014-11       data         data
81     26/10/14 06:58   34.429  data  2014-11       data         data
82     26/10/14 14:51        4  call  2014-11      Three       mobile
83     26/10/14 21:10      637  call  2014-11      Tesco       mobile
84     26/10/14 21:22       28  call  2014-11     Meteor       mobile
85     26/10/14 21:38       62  call  2014-11      Three       mobile
86     27/10/14 01:45        3  call  2014-11      Tesco       mobile
87     27/10/14 06:58   34.429  data  2014-11       data         data
88     27/10/14 11:03      146  call  2014-11      Three       mobile
89     27/10/14 16:30       48  call  2014-11      Three       mobile
90     27/10/14 19:20      862  call  2014-11      Three       mobile
91     27/10/14 19:55       25  call  2014-11      Three       mobile
92     28/10/14 06:58   34.429  data  2014-11       data         data
93     28/10/14 16:39      833  call  2014-11   landline     landline
94     28/10/14 20:44      206  call  2014-11      Tesco       mobile
95     29/10/14 06:58   34.429  data  2014-11       data         data
96     29/10/14 12:56      442  call  2014-11   Vodafone       mobile
97     30/10/14 06:58   34.429  data  2014-11       data         data
98     30/10/14 14:31      463  call  2014-11   Vodafone       mobile
99     30/10/14 19:48        4  call  2014-11   Vodafone       mobile
100    30/10/14 20:02        4  call  2014-11     Meteor       mobile
101    31/10/14 06:58   34.429  data  2014-11       data         data
102    31/10/14 07:46        1   sms  2014-11   Vodafone       mobile
103    31/10/14 08:00        1   sms  2014-11   Vodafone       mobile
104    31/10/14 13:26        5  call  2014-11      Three       mobile
105    31/10/14 13:27     1234  call  2014-11      Tesco       mobile
106    31/10/14 14:10       43  call  2014-11      Three       mobile
107    31/10/14 18:29        1   sms  2014-11      Three       mobile
108    31/10/14 18:29        1   sms  2014-11      Three       mobile
109    31/10/14 18:30      483  call  2014-11     Meteor       mobile
110    31/10/14 18:39        3  call  2014-11      Tesco       mobile
111    01/11/14 06:58   34.429  data  2014-11       data         data
112    01/11/14 15:13      955  call  2014-11   Vodafone       mobile
113    01/11/14 17:54        4  call  2014-11      Tesco       mobile
114    02/11/14 06:58   34.429  data  2014-11       data         data
115    02/11/14 14:34      459  call  2014-11      Three       mobile
116    02/11/14 15:44     1023  call  2014-11      Three       mobile
117    02/11/14 19:16     1025  call  2014-11      Three       mobile
118    02/11/14 21:42      169  call  2014-11     Meteor       mobile
119    02/11/14 22:55        8  call  2014-11     Meteor       mobile
120    03/11/14 06:58   34.429  data  2014-11       data         data
121    03/11/14 08:40        1   sms  2014-11    special      special
122    03/11/14 10:30      135  call  2014-11      Three       mobile
123    03/11/14 10:37        7  call  2014-11   Vodafone       mobile
124    03/11/14 10:47       37  call  2014-11   Vodafone       mobile
125    03/11/14 14:04        1   sms  2014-11   Vodafone       mobile
126    03/11/14 15:27        5  call  2014-11      Three       mobile
127    03/11/14 16:07      123  call  2014-11   landline     landline
128    03/11/14 16:10        4  call  2014-11      Tesco       mobile
129    03/11/14 17:03       90  call  2014-11   Vodafone       mobile
130    03/11/14 22:36        3  call  2014-11      Tesco       mobile
131    04/11/14 06:58   34.429  data  2014-11       data         data
132    04/11/14 11:58        1   sms  2014-11   Vodafone       mobile
133    04/11/14 11:58        1   sms  2014-11   Vodafone       mobile
134    04/11/14 13:12        1   sms  2014-11      Three       mobile
135    04/11/14 14:05        1   sms  2014-11      Three       mobile
136    04/11/14 14:26        1  call  2014-11  voicemail    voicemail
137    04/11/14 14:26       98  call  2014-11  voicemail    voicemail
138    04/11/14 16:13        1   sms  2014-11      Three       mobile
139    04/11/14 16:19        8  call  2014-11     Meteor       mobile
140    04/11/14 16:22        9  call  2014-11     Meteor       mobile
141    04/11/14 16:24        4  call  2014-11     Meteor       mobile
142    04/11/14 16:34        1   sms  2014-11      Three       mobile
143    04/11/14 16:39        1   sms  2014-11     Meteor       mobile
144    04/11/14 16:41        1   sms  2014-11     Meteor       mobile
145    04/11/14 16:45        1   sms  2014-11      Three       mobile
146    04/11/14 18:26        4  call  2014-11      Tesco       mobile
147    04/11/14 20:15       11  call  2014-11      Three       mobile
148    04/11/14 20:15        1   sms  2014-11     Meteor       mobile
149    04/11/14 20:15        1   sms  2014-11     Meteor       mobile
150    04/11/14 20:16      166  call  2014-11     Meteor       mobile
151    05/11/14 06:58   34.429  data  2014-11       data         data
152    05/11/14 10:59       55  call  2014-11      Three       mobile
153    05/11/14 11:30        1   sms  2014-11   Vodafone       mobile
154    05/11/14 11:43        1   sms  2014-11   Vodafone       mobile
155    05/11/14 12:43        1   sms  2014-11   Vodafone       mobile
156    05/11/14 19:35       29  call  2014-11   Vodafone       mobile
157    06/11/14 01:02        1   sms  2014-11   Vodafone       mobile
158    06/11/14 01:02        1   sms  2014-11   Vodafone       mobile
159    06/11/14 06:58   34.429  data  2014-11       data         data
160    06/11/14 09:04        1   sms  2014-11   Vodafone       mobile
161    06/11/14 09:05        1   sms  2014-11   Vodafone       mobile
162    06/11/14 09:47      150  call  2014-11   Vodafone       mobile
163    06/11/14 09:50       89  call  2014-11      Three       mobile
164    06/11/14 09:52       75  call  2014-11     Meteor       mobile
165    06/11/14 09:54        5  call  2014-11      Three       mobile
166    06/11/14 11:47        8  call  2014-11   Vodafone       mobile
167    06/11/14 14:52        1   sms  2014-11   Vodafone       mobile
168    06/11/14 18:02      279  call  2014-11      Tesco       mobile
169    06/11/14 18:07      452  call  2014-11   Vodafone       mobile
170    07/11/14 06:58   34.429  data  2014-11       data         data
171    07/11/14 09:33     1205  call  2014-11   Vodafone       mobile
172    07/11/14 17:51      218  call  2014-11      Three       mobile
173    07/11/14 21:04        1   sms  2014-11   Vodafone       mobile
174    07/11/14 21:10        1   sms  2014-11   Vodafone       mobile
175    07/11/14 21:12        1   sms  2014-11   Vodafone       mobile
176    07/11/14 21:12        1   sms  2014-11   Vodafone       mobile
177    07/11/14 21:19        1   sms  2014-11   Vodafone       mobile
178    07/11/14 21:25        1   sms  2014-11   Vodafone       mobile
179    07/11/14 21:31        1   sms  2014-11   Vodafone       mobile
180    07/11/14 21:31        1   sms  2014-11   Vodafone       mobile
181    07/11/14 22:04        1   sms  2014-11   Vodafone       mobile
182    08/11/14 06:58   34.429  data  2014-11       data         data
183    08/11/14 16:33       41  call  2014-11      Three       mobile
184    08/11/14 18:18        6  call  2014-11      Tesco       mobile
185    09/11/14 01:41        1   sms  2014-11      Three       mobile
186    09/11/14 01:49        1   sms  2014-11      Three       mobile
187    09/11/14 01:50        1   sms  2014-11      Three       mobile
188    09/11/14 02:04        1   sms  2014-11      Three       mobile
189    09/11/14 06:58   34.429  data  2014-11       data         data
190    09/11/14 19:21       14  call  2014-11      Tesco       mobile
191    09/11/14 22:09        3  call  2014-11      Three       mobile
192    10/11/14 06:58   34.429  data  2014-11       data         data
193    10/11/14 09:29      178  call  2014-11   Vodafone       mobile
194    10/11/14 11:36      412  call  2014-11      Three       mobile
195    10/11/14 14:59       13  call  2014-11      Three       mobile
196    10/11/14 15:15      459  call  2014-11      Three       mobile
197    10/11/14 18:19        1   sms  2014-11      Three       mobile
198    10/11/14 18:34        1   sms  2014-11      Three       mobile
199    11/11/14 06:58   34.429  data  2014-11       data         data
200    11/11/14 09:28        3  call  2014-11   Vodafone       mobile
201    11/11/14 11:32        3  call  2014-11   Vodafone       mobile
202    11/11/14 11:37        1   sms  2014-11      Three       mobile
203    11/11/14 12:39       36  call  2014-11      Three       mobile
204    11/11/14 14:13        1   sms  2014-11     Meteor       mobile
205    11/11/14 14:20        1   sms  2014-11     Meteor       mobile
206    11/11/14 14:41        1   sms  2014-11     Meteor       mobile
207    11/11/14 19:56        1   sms  2014-11      Three       mobile
208    12/11/14 06:58   34.429  data  2014-11       data         data
209    12/11/14 10:48        1   sms  2014-11   Vodafone       mobile
210    12/11/14 10:48        1   sms  2014-11      Three       mobile
211    12/11/14 10:48        1   sms  2014-11   Vodafone       mobile
212    12/11/14 10:49        1   sms  2014-11      Three       mobile
213    12/11/14 12:04        1   sms  2014-11      Three       mobile
214    12/11/14 13:49        1   sms  2014-11   Vodafone       mobile
215    12/11/14 16:16        1   sms  2014-11   Vodafone       mobile
216    12/11/14 16:19        4  call  2014-11   landline     landline
217    12/11/14 16:42        1   sms  2014-11   Vodafone       mobile
218    12/11/14 16:42        1   sms  2014-11   Vodafone       mobile
219    12/11/14 17:14        1   sms  2014-11   Vodafone       mobile
220    12/11/14 17:14        1   sms  2014-11   Vodafone       mobile
221    12/11/14 17:49        1   sms  2014-11      Three       mobile
222    12/11/14 17:56      145  call  2014-11      Three       mobile
223    12/11/14 17:59     1001  call  2014-11      Three       mobile
224    12/11/14 19:01        7  call  2014-11   Vodafone       mobile
225    12/11/14 19:18        1   sms  2014-11      Three       mobile
226    12/11/14 19:18        1   sms  2014-11      Three       mobile
227    12/11/14 19:20        1   sms  2014-11   Vodafone       mobile
228    13/11/14 06:58   34.429  data  2014-12       data         data
229    13/11/14 22:30        1   sms  2014-11      Three       mobile
230    13/11/14 22:31        1   sms  2014-11   Vodafone       mobile
231    14/11/14 06:58   34.429  data  2014-12       data         data
232    14/11/14 17:24      124  call  2014-12  voicemail    voicemail
233    14/11/14 17:28        1   sms  2014-12   Vodafone       mobile
234    15/11/14 06:58   34.429  data  2014-12       data         data
235    16/11/14 06:58   34.429  data  2014-12       data         data
236    16/11/14 14:05        4  call  2014-12   Vodafone       mobile
237    17/11/14 06:58   34.429  data  2014-12       data         data
238    18/11/14 06:58   34.429  data  2014-12       data         data
239    18/11/14 08:22        1   sms  2014-12   Vodafone       mobile
240    18/11/14 08:29        1   sms  2014-12   Vodafone       mobile
241    18/11/14 08:29        1   sms  2014-12   Vodafone       mobile
242    18/11/14 08:33        1   sms  2014-12   Vodafone       mobile
243    18/11/14 08:34        1   sms  2014-12   Vodafone       mobile
244    18/11/14 08:34        1   sms  2014-12   Vodafone       mobile
245    18/11/14 08:39        1   sms  2014-12   Vodafone       mobile
246    18/11/14 08:42        1   sms  2014-12   Vodafone       mobile
247    18/11/14 08:45        1   sms  2014-12   Vodafone       mobile
248    18/11/14 09:35        1   sms  2014-12   Vodafone       mobile
249    19/11/14 06:58   34.429  data  2014-12       data         data
250    19/11/14 14:05      128  call  2014-12      Tesco       mobile
251    19/11/14 14:11      249  call  2014-12     Meteor       mobile
252    19/11/14 18:56     2120  call  2014-12      Three       mobile
253    19/11/14 22:48        1   sms  2014-12   Vodafone       mobile
254    20/11/14 06:58   34.429  data  2014-12       data         data
255    20/11/14 14:57       71  call  2014-12  voicemail    voicemail
256    20/11/14 14:59       56  call  2014-12      Three       mobile
257    20/11/14 16:22        1   sms  2014-12     Meteor       mobile
258    20/11/14 19:08        9  call  2014-12      Three       mobile
259    20/11/14 21:03        3  call  2014-12      Three       mobile
260    20/11/14 21:03        3  call  2014-12      Three       mobile
261    21/11/14 00:17       17  call  2014-12      Tesco       mobile
262    21/11/14 01:13        1   sms  2014-12   Vodafone       mobile
263    21/11/14 06:58   34.429  data  2014-12       data         data
264    21/11/14 10:29        1   sms  2014-12     Meteor       mobile
265    21/11/14 10:29        1   sms  2014-12     Meteor       mobile
266    21/11/14 10:30        1   sms  2014-12     Meteor       mobile
267    21/11/14 11:29        8  call  2014-12   landline     landline
268    21/11/14 11:31      982  call  2014-12   Vodafone       mobile
269    21/11/14 11:49       11  call  2014-12   landline     landline
270    21/11/14 11:50       34  call  2014-12      Three       mobile
271    21/11/14 11:50        8  call  2014-12      Three       mobile
272    21/11/14 13:31      600  call  2014-12      Tesco       mobile
273    21/11/14 18:07      244  call  2014-12     Meteor       mobile
274    22/11/14 02:10      186  call  2014-12      Tesco       mobile
275    22/11/14 06:58   34.429  data  2014-12       data         data
276    22/11/14 12:02       75  call  2014-12     Meteor       mobile
277    22/11/14 12:10       90  call  2014-12   Vodafone       mobile
278    22/11/14 14:30       13  call  2014-12   Vodafone       mobile
279    22/11/14 14:33       20  call  2014-12   Vodafone       mobile
280    22/11/14 14:34        2  call  2014-12   Vodafone       mobile
281    23/11/14 06:58   34.429  data  2014-12       data         data
282    23/11/14 13:24      208  call  2014-12      Three       mobile
283    23/11/14 16:10      107  call  2014-12      Three       mobile

In [77]:
"""
Analyzing Data
_________________

Mobile Bill Fields.
-------------------
index - all the records are indexed from 1 to 130
DATE  - is a date of particular row when call has been made.
duration - i guess it is in seconds , duration for which internet is used or call has been made.
ITEM --- it clarify what was medium like data or call
month - is ofcourse month 
Network - what was destination network or internet usage
network_type - again voice call or internet data or audio call 
"""
print(" ")

In [78]:
"""
Cleaning of Data
___________________
"""
print(" ")

In [79]:
"""
Observation:
a) columns on the top few are capital letter and few are in small letters , hardly make difference but in visualization 
it will not look good. Lets fix that.
"""
my_phone_data_table.columns = [ x.lower() for x in my_phone_data_table]

In [80]:
my_phone_data_table.columns

Index(['date', 'duration', 'item', 'month', 'network', 'network_type'], dtype='object')

In [81]:
# Getting info about index
my_phone_data_table.index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            820, 821, 822, 823, 824, 825, 826, 827, 828, 829],
           dtype='int64', name='index', length=830)

In [82]:
type(my_phone_data_table.index)

pandas.core.indexes.numeric.Int64Index

In [83]:
# Getting info about Columns
my_phone_data_table.columns

Index(['date', 'duration', 'item', 'month', 'network', 'network_type'], dtype='object')

In [84]:
type(my_phone_data_table.columns)

pandas.core.indexes.base.Index

In [87]:
"""
Observation:
b) Now without giving second thought , Lets replace all the blank Values with NaN
"""
print(" ")

In [88]:
# Lets go ahead and replade blank values with NaN.
my_phone_data_table.replace(' ', np.nan, inplace=True)

In [89]:
# Lets print those lines which have blank values.

# I need to select the column names which are having Nan in them
null_columns = my_phone_data_table.columns[my_phone_data_table.isnull().any()]
null_columns

Index(['duration', 'item', 'network', 'network_type'], dtype='object')

In [90]:
type(null_columns)

pandas.core.indexes.base.Index

In [91]:
# Now lets lets calculate how Many Nan Values are there in total in each column.
print("_________________________________________")
print("Below is count of each columns which have null values")
my_phone_data_table[null_columns].isnull().sum()

_________________________________________
Below is count of each columns which have null values

duration        1
item            3
network         1
network_type    3
dtype: int64

In [92]:
# SO we observed we have 3 rows in item and network_type , And 1 row in duration and network.   

# I am intrested in seeing those 3 records where network_type is NaN
# Row Number - 13, 305, 311
my_phone_data_table.loc[my_phone_data_table['network_type'].isnull()]

                 date duration  item    month network network_type
index
13     17/10/14 06:58   34.429  data  2014-11     NaN          NaN
305    26/11/14 06:58   34.429  data  2014-12    data          NaN
311    26/11/14 08:13       10   NaN  2014-12   Three          NaN

In [93]:
# I am intrested in seeing those 3 records where item is NaN
# Row Number - 307, 309, 311
my_phone_data_table.loc[my_phone_data_table['item'].isnull()]

                 date duration item    month   network network_type
index
307    26/11/14 07:15        1  NaN  2014-12  Vodafone       mobile
309    26/11/14 07:59        4  NaN  2014-12     Three       mobile
311    26/11/14 08:13       10  NaN  2014-12     Three          NaN

In [94]:
# Now is i am intrested in those 2 records / rows where network , duration is NaN
# Row Number - 13 and 829
my_phone_data_table.loc[my_phone_data_table['network'].isnull() | my_phone_data_table['duration'].isnull()]

                 date duration  item    month network network_type
index
13     17/10/14 06:58   34.429  data  2014-11     NaN          NaN
829    14/03/15 00:16      NaN   sms  2015-03   world        world

In [95]:
# printing a complete record with all columns where  any column is nan

# you can write a big query like in last query you looked at network and duration with one command , But what you will do 
# if you have datafame with 10000 columsn.
my_phone_data_table[my_phone_data_table.isnull().any(axis=1)]

                 date duration  item    month   network network_type
index
13     17/10/14 06:58   34.429  data  2014-11       NaN          NaN
305    26/11/14 06:58   34.429  data  2014-12      data          NaN
307    26/11/14 07:15        1   NaN  2014-12  Vodafone       mobile
309    26/11/14 07:59        4   NaN  2014-12     Three       mobile
311    26/11/14 08:13       10   NaN  2014-12     Three          NaN
829    14/03/15 00:16      NaN   sms  2015-03     world        world

In [96]:
# printing a record where  any column is nan , but print only those columns not extra data
my_phone_data_table[my_phone_data_table.isnull().any(axis=1)][null_columns].head()

      duration  item   network network_type
index
13      34.429  data       NaN          NaN
305     34.429  data      data          NaN
307          1   NaN  Vodafone       mobile
309          4   NaN     Three       mobile
311         10   NaN     Three          NaN

In [97]:
# print record number 13
my_phone_data_table.loc[13]

date            17/10/14 06:58
duration                34.429
item                      data
month                  2014-11
network                    NaN
network_type               NaN
Name: 13, dtype: object

In [98]:
# print record from 0 to 4 and i need only 0,1,2 columns
my_phone_data_table.iloc[0:5, 0:3]

                 date duration  item
index
0      15/10/14 06:58   34.429  data
1      15/10/14 06:58       13  call
2      15/10/14 14:46       23  call
3      15/10/14 14:48        4  call
4      15/10/14 17:27        4  call

In [99]:
"""
Lets work on network_type = Nan , I have to fill them .





Now one idea is to see all the Unique values in  network_type
"""

'\nLets work on network_type = Nan , I have to fill them .\n\n\n\n\n\nNow one idea is to see all the Unique values in  network_type\n'

In [100]:
my_phone_data_table['network_type'].value_counts()

mobile       600
data         148
landline      42
voicemail     27
world          7
special        3
Name: network_type, dtype: int64

In [101]:
my_phone_data_table['network_type'].describe()

count        827
unique         6
top       mobile
freq         600
Name: network_type, dtype: object

In [102]:
# Lets print all records again where network_type is NaN . i.e .value_counts() saying 3 special whats that 

my_phone_data_table[my_phone_data_table['network_type'].isnull()]

                 date duration  item    month network network_type
index
13     17/10/14 06:58   34.429  data  2014-11     NaN          NaN
305    26/11/14 06:58   34.429  data  2014-12    data          NaN
311    26/11/14 08:13       10   NaN  2014-12   Three          NaN

In [103]:
# Now i decided to drop these above 3 rows from mt DataFrame/Table

my_phone_data_table = my_phone_data_table[pd.notnull(my_phone_data_table['network_type'])]

In [104]:
# Validate that those records are dropped.
my_phone_data_table[my_phone_data_table['network_type'].isnull()]

Empty DataFrame
Columns: [date, duration, item, month, network, network_type]
Index: []

In [105]:
"""
Observation:
# Now i want to view the records/row where duration column is NaN
# Once i view is i will replace the NaN with median of column named as duration.
Note :- i know this is incorrect for this particular data , But i am learner .
"""
my_phone_data_table[my_phone_data_table['duration'].isnull()]

                 date duration item    month network network_type
index
829    14/03/15 00:16      NaN  sms  2015-03   world        world

In [106]:
median_of_duration = my_phone_data_table['duration'].median()
median_of_duration

24.5

In [107]:
my_phone_data_table['duration'].fillna(value=median_of_duration, inplace=True)

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5430: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [108]:
my_phone_data_table[my_phone_data_table['duration'].isnull()]

Empty DataFrame
Columns: [date, duration, item, month, network, network_type]
Index: []

In [109]:
# print record from 0 to 4 and i need only 0,1,2 columns
my_phone_data_table.iloc[823:829, :]

                 date duration  item    month   network network_type
index
826    13/03/15 00:39        1   sms  2015-03  Vodafone       mobile
827    13/03/15 06:58   34.429  data  2015-03      data         data
828    14/03/15 00:13        1   sms  2015-03     world        world
829    14/03/15 00:16     24.5   sms  2015-03     world        world

In [110]:
"""
Observation:
Lets tak about record 13 , I want to fill both columns network and network_type with a word called as data.
"""
my_phone_data_table[['network', 'network_type']] = my_phone_data_table[['network', 'network_type']].fillna(value='data')

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

In [112]:
"""
Note:
1. I could have used any of below both should have same result.

my_phone_data_table['duration'].fillna(value=median_of_duration, inplace=True)
my_phone_data_table['duration'] = my_phone_data_table['duration'].fillna(value=median_of_duration)

2. See the difference in specifying column values.
my_phone_data_table[['network', 'network_type']] = my_phone_data_table[['network', 'network_type']].fillna(value='data')
my_phone_data_table['duration'] = my_phone_data_table['duration'].fillna(value=median_of_duration)


"""
print(" ")

In [113]:
"""
Now lets again validate if any row of any column have NaN
"""
my_phone_data_table[my_phone_data_table.isnull().any(axis=1)]

                 date duration item    month   network network_type
index
307    26/11/14 07:15        1  NaN  2014-12  Vodafone       mobile
309    26/11/14 07:59        4  NaN  2014-12     Three       mobile

In [114]:
# Lets drop those 2 columns which have Nan
my_phone_data_table = my_phone_data_table[pd.notnull(my_phone_data_table['item'])]

In [115]:
# Final Validation check if now i have any Null Value.
my_phone_data_table[my_phone_data_table.isnull().any(axis=1)]

Empty DataFrame
Columns: [date, duration, item, month, network, network_type]
Index: []

In [116]:
my_column_series = my_phone_data_table.columns
my_column_series

Index(['date', 'duration', 'item', 'month', 'network', 'network_type'], dtype='object')

In [117]:
"""
Observation:
You need to rese the index as you deleted rows which corrupts your index numbering .
# But it is good practice to save the old index first , before you reset the index
"""
my_phone_data_table["old_dropped_index"] = my_phone_data_table.index

In [118]:
my_phone_data_table = my_phone_data_table.reset_index(drop=True)

In [119]:
my_phone_data_table

,date,duration,item,...,network,network_type,old_dropped_index
0,15/10/14 06:58,34.429,data,...,data,data,0
1,15/10/14 06:58,13,call,...,Vodafone,mobile,1
2,15/10/14 14:46,23,call,...,Meteor,mobile,2
3,15/10/14 14:48,4,call,...,Tesco,mobile,3
4,15/10/14 17:27,4,call,...,Tesco,mobile,4
5,15/10/14 18:55,4,call,...,Tesco,mobile,5
6,16/10/14 06:58,34.429,data,...,data,data,6
7,16/10/14 15:01,602,call,...,Three,mobile,7
8,16/10/14 15:12,1050,call,...,Three,mobile,8
9,16/10/14 15:30,19,call,...,voicemail,voicemail,9
10,16/10/14 16:21,1183,call,...,Three,mobile,10
11,16/10/14 22:18,1,sms,...,Meteor,mobile,11
12,16/10/14 22:21,1,sms,...,Meteor,mobile,12
13,17/10/14 10:53,1,sms,...,Tesco,mobile,14
14,17/10/14 11:19,1,sms,...,Tesco,mobile,15
15,17/10/14 11:20,1,sms,...,Meteor,mobile,16
16,17/10/14 17:22,1,sms,...,Vodafone,mobile,17
17,17/10/14 17:23,1,sms,...,Vodafone,mobile,18
18,17/10/14 17:26,92,call,...,Three,mobile,19
19,17/10/14 17:29,4,call,...,Vodafone,mobile,20
20,17/10/14 17:30,375,call,...,Tesco,mobile,21
21,17/10/14 17:42,1,sms,...,Vodafone,mobile,22
22,17/10/14 17:44,1,sms,...,Vodafone,mobile,23
23,17/10/14 17:44,1,sms,...,Vodafone,mobile,24
24,17/10/14 17:44,1,sms,...,Vodafone,mobile,25
25,18/10/14 06:58,34.429,data,...,data,data,26
26,18/10/14 11:51,783,call,...,Tesco,mobile,27
27,18/10/14 12:06,4,call,...,Vodafone,mobile,28
28,18/10/14 12:06,3,call,...,Vodafone,mobile,29
29,18/10/14 13:08,101,call,...,Vodafone,mobile,30
30,18/10/14 13:10,1714,call,...,Three,mobile,31
31,18/10/14 14:01,96,call,...,voicemail,voicemail,32
32,18/10/14 18:52,1,sms,...,Vodafone,mobile,33
33,18/10/14 20:44,384,call,...,Three,mobile,34
34,18/10/14 21:04,4,call,...,Three,mobile,35
35,18/10/14 21:06,1,sms,...,Three,mobile,36
36,18/10/14 21:23,1,sms,...,Vodafone,mobile,37
37,18/10/14 22:37,1,sms,...,Three,mobile,38
38,19/10/14 06:58,34.429,data,...,data,data,39
39,19/10/14 14:47,53,call,...,Three,mobile,40
40,19/10/14 15:46,86,call,...,Tesco,mobile,41
41,19/10/14 16:21,23,call,...,Three,mobile,42
42,19/10/14 16:30,38,call,...,Three,mobile,43
43,19/10/14 20:25,428,call,...,Three,mobile,44
44,20/10/14 06:58,34.429,data,...,data,data,45
45,20/10/14 09:43,69,call,...,voicemail,voicemail,46
46,20/10/14 09:43,18,call,...,voicemail,voicemail,47
47,20/10/14 13:55,3,call,...,Vodafone,mobile,48
48,20/10/14 13:56,6,call,...,landline,landline,49
49,20/10/14 18:14,5,call,...,Tesco,mobile,50
50,20/10/14 18:24,131,call,...,Vodafone,mobile,51
51,20/10/14 19:59,1,sms,...,Vodafone,mobile,52
52,20/10/14 20:16,1,sms,...,Vodafone,mobile,53
53,21/10/14 06:58,34.429,data,...,data,data,54
54,21/10/14 16:17,550,call,...,Three,mobile,55
55,22/10/14 06:58,34.429,data,...,data,data,56
56,22/10/14 12:04,7,call,...,Three,mobile,57
57,23/10/14 06:58,34.429,data,...,data,data,58
58,23/10/14 08:34,1940,call,...,landline,landline,59
59,23/10/14 09:45,281,call,...,Meteor,mobile,60
60,23/10/14 10:46,1,sms,...,Tesco,mobile,61
61,23/10/14 10:54,1,sms,...,Vodafone,mobile,62
62,23/10/14 11:17,1,sms,...,Vodafone,mobile,63
63,23/10/14 11:25,24,call,...,Vodafone,mobile,64
64,23/10/14 17:48,263,call,...,Meteor,mobile,65
65,24/10/14 06:58,34.429,data,...,data,data,66
66,24/10/14 13:35,1,sms,...,Vodafone,mobile,67
67,24/10/14 13:39,1,sms,...,Vodafone,mobile,68
68,24/10/14 13:39,1,sms,...,Vodafone,mobile,69
69,24/10/14 13:47,1,sms,...,Vodafone,mobile,70
70,24/10/14 13:48,1,sms,...,Vodafone,mobile,71
71,24/10/14 13:50,1,sms,...,Vodafone,mobile,72
72,24/10/14 13:57,1,sms,...,Vodafone,mobile,73
73,24/10/14 13:57,1,sms,...,Vodafone,mobile,74
74,24/10/14 14:20,1,sms,...,Three,mobile,75
75,24/10/14 14:27,1,sms,...,Vodafone,mobile,76
76,24/10/14 18:29,1,sms,...,Vodafone,mobile,77
77,24/10/14 18:33,387,call,...,Tesco,mobile,78
78,24/10/14 18:40,1,sms,...,Vodafone,mobile,79
79,25/10/14 06:58,34.429,data,...,data,data,80
80,26/10/14 06:58,34.429,data,...,data,data,81
81,26/10/14 14:51,4,call,...,Three,mobile,82
82,26/10/14 21:10,637,call,...,Tesco,mobile,83
83,26/10/14 21:22,28,call,...,Meteor,mobile,84
84,26/10/14 21:38,62,call,...,Three,mobile,85
85,27/10/14 01:45,3,call,...,Tesco,mobile,86
86,27/10/14 06:58,34.429,data,...,data,data,87
87,27/10/14 11:03,146,call,...,Three,mobile,88
88,27/10/14 16:30,48,call,...,Three,mobile,89
89,27/10/14 19:20,862,call,...,Three,mobile,90
90,27/10/14 19:55,25,call,...,Three,mobile,91
91,28/10/14 06:58,34.429,data,...,data,data,92
92,28/10/14 16:39,833,call,...,landline,landline,93
93,28/10/14 20:44,206,call,...,Tesco,mobile,94
94,29/10/14 06:58,34.429,data,...,data,data,95
95,29/10/14 12:56,442,call,...,Vodafone,mobile,96
96,30/10/14 06:58,34.429,data,...,data,data,97
97,30/10/14 14:31,463,call,...,Vodafone,mobile,98
98,30/10/14 19:48,4,call,...,Vodafone,mobile,99
99,30/10/14 20:02,4,call,...,Meteor,mobile,100
100,31/10/14 06:58,34.429,data,...,data,data,101
101,31/10/14 07:46,1,sms,...,Vodafone,mobile,102
102,31/10/14 08:00,1,sms,...,Vodafone,mobile,103
103,31/10/14 13:26,5,call,...,Three,mobile,104
104,31/10/14 13:27,1234,call,...,Tesco,mobile,105
105,31/10/14 14:10,43,call,...,Three,mobile,106
106,31/10/14 18:29,1,sms,...,Three,mobile,107
107,31/10/14 18:29,1,sms,...,Three,mobile,108
108,31/10/14 18:30,483,call,...,Meteor,mobile,109
109,31/10/14 18:39,3,call,...,Tesco,mobile,110
110,01/11/14 06:58,34.429,data,...,data,data,111
111,01/11/14 15:13,955,call,...,Vodafone,mobile,112
112,01/11/14 17:54,4,call,...,Tesco,mobile,113
113,02/11/14 06:58,34.429,data,...,data,data,114
114,02/11/14 14:34,459,call,...,Three,mobile,115
115,02/11/14 15:44,1023,call,...,Three,mobile,116
116,02/11/14 19:16,1025,call,...,Three,mobile,117
117,02/11/14 21:42,169,call,...,Meteor,mobile,118
118,02/11/14 22:55,8,call,...,Meteor,mobile,119
119,03/11/14 06:58,34.429,data,...,data,data,120
120,03/11/14 08:40,1,sms,...,special,special,121
121,03/11/14 10:30,135,call,...,Three,mobile,122
122,03/11/14 10:37,7,call,...,Vodafone,mobile,123
123,03/11/14 10:47,37,call,...,Vodafone,mobile,124
124,03/11/14 14:04,1,sms,...,Vodafone,mobile,125
125,03/11/14 15:27,5,call,...,Three,mobile,126
126,03/11/14 16:07,123,call,...,landline,landline,127
127,03/11/14 16:10,4,call,...,Tesco,mobile,128
128,03/11/14 17:03,90,call,...,Vodafone,mobile,129
129,03/11/14 22:36,3,call,...,Tesco,mobile,130
130,04/11/14 06:58,34.429,data,...,data,data,131
131,04/11/14 11:58,1,sms,...,Vodafone,mobile,132
132,04/11/14 11:58,1,sms,...,Vodafone,mobile,133
133,04/11/14 13:12,1,sms,...,Three,mobile,134
134,04/11/14 14:05,1,sms,...,Three,mobile,135
135,04/11/14 14:26,1,call,...,voicemail,voicemail,136
136,04/11/14 14:26,98,call,...,voicemail,voicemail,137
137,04/11/14 16:13,1,sms,...,Three,mobile,138
138,04/11/14 16:19,8,call,...,Meteor,mobile,139
139,04/11/14 16:22,9,call,...,Meteor,mobile,140
140,04/11/14 16:24,4,call,...,Meteor,mobile,141
141,04/11/14 16:34,1,sms,...,Three,mobile,142
142,04/11/14 16:39,1,sms,...,Meteor,mobile,143
143,04/11/14 16:41,1,sms,...,Meteor,mobile,144
144,04/11/14 16:45,1,sms,...,Three,mobile,145
145,04/11/14 18:26,4,call,...,Tesco,mobile,146
146,04/11/14 20:15,11,call,...,Three,mobile,147
147,04/11/14 20:15,1,sms,...,Meteor,mobile,148
148,04/11/14 20:15,1,sms,...,Meteor,mobile,149
149,04/11/14 20:16,166,call,...,Meteor,mobile,150
150,05/11/14 06:58,34.429,data,...,data,data,151
151,05/11/14 10:59,55,call,...,Three,mobile,152
152,05/11/14 11:30,1,sms,...,Vodafone,mobile,153
153,05/11/14 11:43,1,sms,...,Vodafone,mobile,154
154,05/11/14 12:43,1,sms,...,Vodafone,mobile,155
155,05/11/14 19:35,29,call,...,Vodafone,mobile,156
156,06/11/14 01:02,1,sms,...,Vodafone,mobile,157
157,06/11/14 01:02,1,sms,...,Vodafone,mobile,158
158,06/11/14 06:58,34.429,data,...,data,data,159
159,06/11/14 09:04,1,sms,...,Vodafone,mobile,160
160,06/11/14 09:05,1,sms,...,Vodafone,mobile,161
161,06/11/14 09:47,150,call,...,Vodafone,mobile,162
162,06/11/14 09:50,89,call,...,Three,mobile,163
163,06/11/14 09:52,75,call,...,Meteor,mobile,164
164,06/11/14 09:54,5,call,...,Three,mobile,165
165,06/11/14 11:47,8,call,...,Vodafone,mobile,166
166,06/11/14 14:52,1,sms,...,Vodafone,mobile,167
167,06/11/14 18:02,279,call,...,Tesco,mobile,168
168,06/11/14 18:07,452,call,...,Vodafone,mobile,169
169,07/11/14 06:58,34.429,data,...,data,data,170
170,07/11/14 09:33,1205,call,...,Vodafone,mobile,171
171,07/11/14 17:51,218,call,...,Three,mobile,172
172,07/11/14 21:04,1,sms,...,Vodafone,mobile,173
173,07/11/14 21:10,1,sms,...,Vodafone,mobile,174
174,07/11/14 21:12,1,sms,...,Vodafone,mobile,175
175,07/11/14 21:12,1,sms,...,Vodafone,mobile,176
176,07/11/14 21:19,1,sms,...,Vodafone,mobile,177
177,07/11/14 21:25,1,sms,...,Vodafone,mobile,178
178,07/11/14 21:31,1,sms,...,Vodafone,mobile,179
179,07/11/14 21:31,1,sms,...,Vodafone,mobile,180
180,07/11/14 22:04,1,sms,...,Vodafone,mobile,181
181,08/11/14 06:58,34.429,data,...,data,data,182
182,08/11/14 16:33,41,call,...,Three,mobile,183
183,08/11/14 18:18,6,call,...,Tesco,mobile,184
184,09/11/14 01:41,1,sms,...,Three,mobile,185
185,09/11/14 01:49,1,sms,...,Three,mobile,186
186,09/11/14 01:50,1,sms,...,Three,mobile,187
187,09/11/14 02:04,1,sms,...,Three,mobile,188
188,09/11/14 06:58,34.429,data,...,data,data,189
189,09/11/14 19:21,14,call,...,Tesco,mobile,190
190,09/11/14 22:09,3,call,...,Three,mobile,191
191,10/11/14 06:58,34.429,data,...,data,data,192
192,10/11/14 09:29,178,call,...,Vodafone,mobile,193
193,10/11/14 11:36,412,call,...,Three,mobile,194
194,10/11/14 14:59,13,call,...,Three,mobile,195
195,10/11/14 15:15,459,call,...,Three,mobile,196
196,10/11/14 18:19,1,sms,...,Three,mobile,197
197,10/11/14 18:34,1,sms,...,Three,mobile,198
198,11/11/14 06:58,34.429,data,...,data,data,199
199,11/11/14 09:28,3,call,...,Vodafone,mobile,200
200,11/11/14 11:32,3,call,...,Vodafone,mobile,201
201,11/11/14 11:37,1,sms,...,Three,mobile,202
202,11/11/14 12:39,36,call,...,Three,mobile,203
203,11/11/14 14:13,1,sms,...,Meteor,mobile,204
204,11/11/14 14:20,1,sms,...,Meteor,mobile,205
205,11/11/14 14:41,1,sms,...,Meteor,mobile,206
206,11/11/14 19:56,1,sms,...,Three,mobile,207
207,12/11/14 06:58,34.429,data,...,data,data,208
208,12/11/14 10:48,1,sms,...,Vodafone,mobile,209
209,12/11/14 10:48,1,sms,...,Three,mobile,210
210,12/11/14 10:48,1,sms,...,Vodafone,mobile,211
211,12/11/14 10:49,1,sms,...,Three,mobile,212
212,12/11/14 12:04,1,sms,...,Three,mobile,213
213,12/11/14 13:49,1,sms,...,Vodafone,mobile,214
214,12/11/14 16:16,1,sms,...,Vodafone,mobile,215
215,12/11/14 16:19,4,call,...,landline,landline,216
216,12/11/14 16:42,1,sms,...,Vodafone,mobile,217
217,12/11/14 16:42,1,sms,...,Vodafone,mobile,218
218,12/11/14 17:14,1,sms,...,Vodafone,mobile,219
219,12/11/14 17:14,1,sms,...,Vodafone,mobile,220
220,12/11/14 17:49,1,sms,...,Three,mobile,221
221,12/11/14 17:56,145,call,...,Three,mobile,222
222,12/11/14 17:59,1001,call,...,Three,mobile,223
223,12/11/14 19:01,7,call,...,Vodafone,mobile,224
224,12/11/14 19:18,1,sms,...,Three,mobile,225
225,12/11/14 19:18,1,sms,...,Three,mobile,226
226,12/11/14 19:20,1,sms,...,Vodafone,mobile,227
227,13/11/14 06:58,34.429,data,...,data,data,228
228,13/11/14 22:30,1,sms,...,Three,mobile,229
229,13/11/14 22:31,1,sms,...,Vodafone,mobile,230
230,14/11/14 06:58,34.429,data,...,data,data,231
231,14/11/14 17:24,124,call,...,voicemail,voicemail,232
232,14/11/14 17:28,1,sms,...,Vodafone,mobile,233
233,15/11/14 06:58,34.429,data,...,data,data,234
234,16/11/14 06:58,34.429,data,...,data,data,235
235,16/11/14 14:05,4,call,...,Vodafone,mobile,236
236,17/11/14 06:58,34.429,data,...,data,data,237
237,18/11/14 06:58,34.429,data,...,data,data,238
238,18/11/14 08:22,1,sms,...,Vodafone,mobile,239
239,18/11/14 08:29,1,sms,...,Vodafone,mobile,240
240,18/11/14 08:29,1,sms,...,Vodafone,mobile,241
241,18/11/14 08:33,1,sms,...,Vodafone,mobile,242
242,18/11/14 08:34,1,sms,...,Vodafone,mobile,243
243,18/11/14 08:34,1,sms,...,Vodafone,mobile,244
244,18/11/14 08:39,1,sms,...,Vodafone,mobile,245
245,18/11/14 08:42,1,sms,...,Vodafone,mobile,246
246,18/11/14 08:45,1,sms,...,Vodafone,mobile,247
247,18/11/14 09:35,1,sms,...,Vodafone,mobile,248
248,19/11/14 06:58,34.429,data,...,data,data,249
249,19/11/14 14:05,128,call,...,Tesco,mobile,250
250,19/11/14 14:11,249,call,...,Meteor,mobile,251
251,19/11/14 18:56,2120,call,...,Three,mobile,252
252,19/11/14 22:48,1,sms,...,Vodafone,mobile,253
253,20/11/14 06:58,34.429,data,...,data,data,254
254,20/11/14 14:57,71,call,...,voicemail,voicemail,255
255,20/11/14 14:59,56,call,...,Three,mobile,256
256,20/11/14 16:22,1,sms,...,Meteor,mobile,257
257,20/11/14 19:08,9,call,...,Three,mobile,258
258,20/11/14 21:03,3,call,...,Three,mobile,259
259,20/11/14 21:03,3,call,...,Three,mobile,260
260,21/11/14 00:17,17,call,...,Tesco,mobile,261
261,21/11/14 01:13,1,sms,...,Vodafone,mobile,262
262,21/11/14 06:58,34.429,data,...,data,data,263
263,21/11/14 10:29,1,sms,...,Meteor,mobile,264
264,21/11/14 10:29,1,sms,...,Meteor,mobile,265
265,21/11/14 10:30,1,sms,...,Meteor,mobile,266
266,21/11/14 11:29,8,call,...,landline,landline,267
267,21/11/14 11:31,982,call,...,Vodafone,mobile,268
268,21/11/14 11:49,11,call,...,landline,landline,269
269,21/11/14 11:50,34,call,...,Three,mobile,270
270,21/11/14 11:50,8,call,...,Three,mobile,271
271,21/11/14 13:31,600,call,...,Tesco,mobile,272
272,21/11/14 18:07,244,call,...,Meteor,mobile,273
273,22/11/14 02:10,186,call,...,Tesco,mobile,274
274,22/11/14 06:58,34.429,data,...,data,data,275
275,22/11/14 12:02,75,call,...,Meteor,mobile,276
276,22/11/14 12:10,90,call,...,Vodafone,mobile,277
277,22/11/14 14:30,13,call,...,Vodafone,mobile,278
278,22/11/14 14:33,20,call,...,Vodafone,mobile,279
279,22/11/14 14:34,2,call,...,Vodafone,mobile,280
280,23/11/14 06:58,34.429,data,...,data,data,281
281,23/11/14 13:24,208,call,...,Three,mobile,282
282,23/11/14 16:10,107,call,...,Three,mobile,283
283,23/11/14 17:36,55,call,...,Three,mobile,284
284,23/11/14 17:53,5,call,...,Three,mobile,285
285,23/11/14 17:53,20,call,...,Three,mobile,286
286,23/11/14 17:54,2,call,...,Three,mobile,287
287,24/11/14 06:58,34.429,data,...,data,data,288
288,24/11/14 09:40,1,sms,...,Three,mobile,289
289,24/11/14 12:24,4,call,...,Meteor,mobile,290
290,25/11/14 06:58,34.429,data,...,data,data,291
291,25/11/14 11:25,21,call,...,Vodafone,mobile,292
292,25/11/14 16:09,1,sms,...,Meteor,mobile,293
293,25/11/14 16:19,1,sms,...,Meteor,mobile,294
294,25/11/14 17:10,114,call,...,Meteor,mobile,295
295,25/11/14 18:06,1,sms,...,Meteor,mobile,296
296,25/11/14 18:18,81,call,...,Meteor,mobile,297
297,25/11/14 18:47,174,call,...,voicemail,voicemail,298
298,25/11/14 19:10,71,call,...,Tesco,mobile,299
299,25/11/14 19:20,40,call,...,Tesco,mobile,300
300,25/11/14 19:21,29,call,...,voicemail,voicemail,301
301,25/11/14 19:25,37,call,...,Tesco,mobile,302
302,25/11/14 19:26,63,call,...,voicemail,voicemail,303
303,25/11/14 20:39,1,sms,...,Three,mobile,304
304,26/11/14 07:03,14,call,...,Meteor,mobile,306
305,26/11/14 07:57,1,sms,...,Vodafone,mobile,308
306,26/11/14 08:00,1,sms,...,Vodafone,mobile,310
307,26/11/14 08:16,3,call,...,Three,mobile,312
308,26/11/14 08:26,3,call,...,Three,mobile,313
309,26/11/14 08:27,3,call,...,Three,mobile,314
310,26/11/14 09:01,1,sms,...,Meteor,mobile,315
311,26/11/14 11:53,1,sms,...,Meteor,mobile,316
312,26/11/14 11:54,1,sms,...,Meteor,mobile,317
313,26/11/14 11:54,1,sms,...,Meteor,mobile,318
314,26/11/14 11:56,1,sms,...,Meteor,mobile,319
315,26/11/14 17:48,3,call,...,Three,mobile,320
316,27/11/14 06:58,34.429,data,...,data,data,321
317,27/11/14 16:53,1116,call,...,Three,mobile,322
318,27/11/14 18:38,1,sms,...,Three,mobile,323
319,28/11/14 06:58,34.429,data,...,data,data,324
320,28/11/14 13:05,1,sms,...,Three,mobile,325
321,28/11/14 13:12,1,sms,...,Three,mobile,326
322,28/11/14 19:03,143,call,...,Tesco,mobile,327
323,29/11/14 06:58,34.429,data,...,data,data,328
324,29/11/14 14:44,151,call,...,Three,mobile,329
325,30/11/14 06:58,34.429,data,...,data,data,330
326,30/11/14 11:45,1,sms,...,Three,mobile,331
327,30/11/14 11:48,1,sms,...,Three,mobile,332
328,30/11/14 11:48,1,sms,...,Three,mobile,333
329,30/11/14 12:06,1,sms,...,Three,mobile,334
330,30/11/14 14:24,1,sms,...,Three,mobile,335
331,30/11/14 14:44,1,sms,...,Three,mobile,336
332,30/11/14 14:51,4,call,...,Three,mobile,337
333,01/12/14 06:58,34.429,data,...,data,data,338
334,01/12/14 12:51,1,sms,...,Three,mobile,339
335,01/12/14 12:59,1,sms,...,Three,mobile,340
336,02/12/14 06:58,34.429,data,...,data,data,341
337,02/12/14 11:40,526,call,...,Meteor,mobile,342
338,03/12/14 06:58,34.429,data,...,data,data,343
339,03/12/14 15:01,844,call,...,landline,landline,344
340,03/12/14 18:10,383,call,...,Tesco,mobile,345
341,04/12/14 06:58,34.429,data,...,data,data,346
342,04/12/14 13:52,6,call,...,Vodafone,mobile,347
343,04/12/14 15:34,37,call,...,Three,mobile,348
344,04/12/14 16:02,15,call,...,Meteor,mobile,349
345,04/12/14 23:41,71,call,...,voicemail,voicemail,350
346,05/12/14 06:58,34.429,data,...,data,data,351
347,05/12/14 16:49,465,call,...,landline,landline,352
348,05/12/14 18:17,153,call,...,Tesco,mobile,353
349,05/12/14 18:25,826,call,...,Three,mobile,354
350,06/12/14 06:58,34.429,data,...,data,data,355
351,06/12/14 11:33,442,call,...,Meteor,mobile,356
352,06/12/14 18:25,1,sms,...,Vodafone,mobile,357
353,06/12/14 18:26,1,sms,...,Tesco,mobile,358
354,06/12/14 18:26,1,sms,...,Vodafone,mobile,359
355,06/12/14 18:27,1,sms,...,world,world,360
356,06/12/14 18:28,1,sms,...,world,world,361
357,06/12/14 19:40,191,call,...,Meteor,mobile,362
358,07/12/14 06:58,34.429,data,...,data,data,363
359,07/12/14 13:03,99,call,...,voicemail,voicemail,364
360,07/12/14 13:45,428,call,...,Three,mobile,365
361,07/12/14 14:39,3,call,...,Three,mobile,366
362,07/12/14 20:23,727,call,...,Three,mobile,367
363,07/12/14 20:36,33,call,...,Tesco,mobile,368
364,07/12/14 20:37,120,call,...,Three,mobile,369
365,07/12/14 23:22,1,sms,...,world,world,370
366,07/12/14 23:22,1,sms,...,world,world,371
367,08/12/14 06:58,34.429,data,...,data,data,372
368,08/12/14 17:38,55,call,...,Meteor,mobile,373
369,09/12/14 06:58,34.429,data,...,data,data,374
370,09/12/14 18:32,28,call,...,Tesco,mobile,375
371,10/12/14 06:58,34.429,data,...,data,data,376
372,11/12/14 06:58,34.429,data,...,data,data,377
373,12/12/14 06:58,34.429,data,...,data,data,378
374,12/12/14 11:00,112,call,...,Vodafone,mobile,379
375,12/12/14 18:14,52,call,...,Vodafone,mobile,380
376,13/12/14 06:58,34.429,data,...,data,data,381
377,13/12/14 14:56,223,call,...,Three,mobile,382
378,14/12/14 02:05,14,call,...,landline,landline,383
379,14/12/14 02:07,8,call,...,landline,landline,384
380,14/12/14 02:09,74,call,...,landline,landline,385
381,14/12/14 06:58,34.429,data,...,data,data,386
382,14/12/14 15:28,59,call,...,voicemail,voicemail,387
383,14/12/14 19:54,25,call,...,Three,mobile,388
384,15/12/14 06:58,34.429,data,...,data,data,389
385,15/12/14 19:56,1,sms,...,Three,mobile,390
386,15/12/14 19:58,1,sms,...,Three,mobile,391
387,15/12/14 20:03,4,call,...,Three,mobile,392
388,15/12/14 20:10,1,sms,...,Vodafone,mobile,393
389,15/12/14 20:10,1,sms,...,Three,mobile,394
390,15/12/14 23:12,1,sms,...,Three,mobile,395
391,16/12/14 06:58,34.429,data,...,data,data,396
392,17/12/14 06:58,34.429,data,...,data,data,397
393,17/12/14 18:08,1859,call,...,Vodafone,mobile,398
394,17/12/14 23:26,1,sms,...,Vodafone,mobile,399
395,18/12/14 06:58,34.429,data,...,data,data,400
396,18/12/14 12:36,61,call,...,Three,mobile,401
397,18/12/14 15:46,268,call,...,Meteor,mobile,402
398,18/12/14 15:57,192,call,...,Meteor,mobile,403
399,18/12/14 16:10,14,call,...,Meteor,mobile,404
400,18/12/14 17:54,17,call,...,Three,mobile,405
401,18/12/14 19:05,46,call,...,Tesco,mobile,406
402,18/12/14 21:58,4,call,...,Meteor,mobile,407
403,18/12/14 21:59,4,call,...,Meteor,mobile,408
404,19/12/14 06:58,34.429,data,...,data,data,409
405,19/12/14 08:57,1,sms,...,Vodafone,mobile,410
406,19/12/14 10:14,41,call,...,Three,mobile,411
407,19/12/14 12:40,3,call,...,Three,mobile,412
408,19/12/14 12:41,217,call,...,Tesco,mobile,413
409,19/12/14 12:41,18,call,...,Three,mobile,414
410,19/12/14 14:48,58,call,...,Meteor,mobile,415
411,19/12/14 16:49,48,call,...,Tesco,mobile,416

In [121]:
"""
Now  all columns have data and reindexing has been done , lets save new data to csv file
# Typically, I don't want row numbers in my output file, hence index=False.

"""
my_phone_data_table.to_csv('D:\\myPythonProjects\\PandaSummarisingAggregatingGrouping\\phone_bill_NewCleanData.csv', sep=',', index=False , encoding='utf-8')

In [122]:
os.path.isfile('D:\\myPythonProjects\\PandaSummarisingAggregatingGrouping\\phone_bill_NewCleanData.csv')

True